from Plan import Plan
from constants import CLAIMS_PROBABILITY_DISTRIBUTION, PCP_COPAY_DATA, SPS_COPAY_DATA, ER_COPAY_DATA, COINSURANCE_THRESHOLD_DATA, DEDUCTIBLE_THRESHOLD_DATA, MOOP_THRESHOLD_DATA

test_plan = Plan(1, 'Plan 1', 1500, 0.2, 4500, 30, 55, 250)
test_plan.calculate_base_brf(CLAIMS_PROBABILITY_DISTRIBUTION)

test_plan.calculate_indeces(DEDUCTIBLE_THRESHOLD_DATA, COINSURANCE_THRESHOLD_DATA, MOOP_THRESHOLD_DATA)

