from Plan import Plan
from constants import CLAIMS_PROBABILITY_DISTRIBUTION, PCP_COPAY_DATA, SPS_COPAY_DATA, ER_COPAY_DATA, COINSURANCE_THRESHOLD_DATA, DEDUCTIBLE_THRESHOLD_DATA, MOOP_THRESHOLD_DATA

test_plan = Plan(1, 'Plan 1', 1500, 0.2, 4500, 30, 55, 250)

#now you only need to call calculate_plan_brf with all the data
print(test_plan.calculate_plan_brf(
    CLAIMS_PROBABILITY_DISTRIBUTION,
    DEDUCTIBLE_THRESHOLD_DATA,
    COINSURANCE_THRESHOLD_DATA,
    MOOP_THRESHOLD_DATA,
    PCP_COPAY_DATA,
    SPS_COPAY_DATA,
    ER_COPAY_DATA
))